# Form implementation generated from reading ui file 'apps/gui/resources/ui/_bots.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Libraries
from PyQt6 import QtCore, QtGui, QtWidgets


class ConfigBotDesigner(object):
    def setupUi(self, conf_bot):
        conf_bot.setObjectName("conf_bot")
        conf_bot.resize(600, 500)
        conf_bot.setMinimumSize(QtCore.QSize(600, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(conf_bot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_bots = QtWidgets.QLabel(parent=conf_bot)
        self.lbl_bots.setEnabled(True)
        self.lbl_bots.setMinimumSize(QtCore.QSize(10, 10))
        self.lbl_bots.setObjectName("lbl_bots")
        self.horizontalLayout.addWidget(self.lbl_bots)
        self.cmb_bots = QtWidgets.QComboBox(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cmb_bots.sizePolicy().hasHeightForWidth()
        )
        self.cmb_bots.setSizePolicy(sizePolicy)
        self.cmb_bots.setObjectName("cmb_bots")
        self.horizontalLayout.addWidget(self.cmb_bots)
        self.btn_add_bot = QtWidgets.QPushButton(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_add_bot.sizePolicy().hasHeightForWidth()
        )
        self.btn_add_bot.setSizePolicy(sizePolicy)
        self.btn_add_bot.setObjectName("btn_add_bot")
        self.horizontalLayout.addWidget(self.btn_add_bot)
        self.btn_save = QtWidgets.QPushButton(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_save.sizePolicy().hasHeightForWidth()
        )
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tree_configuration = QtWidgets.QTreeWidget(parent=conf_bot)
        self.tree_configuration.setAnimated(True)
        self.tree_configuration.setObjectName("tree_configuration")
        self.tree_configuration.header().setVisible(True)
        self.tree_configuration.header().setMinimumSectionSize(60)
        self.verticalLayout.addWidget(self.tree_configuration)
        self.ly_errors = QtWidgets.QVBoxLayout()
        self.ly_errors.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.ly_errors.setContentsMargins(-1, 0, -1, -1)
        self.ly_errors.setSpacing(10)
        self.ly_errors.setObjectName("ly_errors")
        self.label = QtWidgets.QLabel(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Preferred,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.label.sizePolicy().hasHeightForWidth()
        )
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(0, 20))
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.ly_errors.addWidget(self.label)
        self.lst_errors = QtWidgets.QListWidget(parent=conf_bot)
        self.lst_errors.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Expanding,
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.lst_errors.sizePolicy().hasHeightForWidth()
        )
        self.lst_errors.setSizePolicy(sizePolicy)
        self.lst_errors.setMinimumSize(QtCore.QSize(0, 100))
        self.lst_errors.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lst_errors.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents
        )
        self.lst_errors.setResizeMode(QtWidgets.QListView.ResizeMode.Adjust)
        self.lst_errors.setObjectName("lst_errors")
        self.ly_errors.addWidget(self.lst_errors)
        self.verticalLayout.addLayout(self.ly_errors)

        self.retranslateUi(conf_bot)
        QtCore.QMetaObject.connectSlotsByName(conf_bot)

    def retranslateUi(self, conf_bot):
        conf_bot.setWindowTitle(_("Config Bots"))  # noqa
        self.lbl_bots.setText(_("Bots"))  # noqa
        self.btn_add_bot.setText(_("New"))  # noqa
        self.btn_save.setText(_("Save"))  # noqa
        self.tree_configuration.headerItem().setText(0, _("Key"))  # noqa
        self.label.setText(_("Errors"))  # noqa
        self.tree_configuration.headerItem().setText(1, _("Value"))  # noqa
        self.tree_configuration.setSortingEnabled(False)
