# Form implementation generated from reading ui file 'apps/gui/resources/ui/_bots.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Libraries
from PyQt6 import QtCore, QtGui, QtWidgets


class ConfigBotDesigner(object):
    def setupUi(self, conf_bot):
        conf_bot.setObjectName("conf_bot")
        conf_bot.resize(600, 500)
        conf_bot.setMinimumSize(QtCore.QSize(600, 500))
        self.verticalLayout = QtWidgets.QVBoxLayout(conf_bot)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_bots = QtWidgets.QLabel(parent=conf_bot)
        self.lbl_bots.setEnabled(True)
        self.lbl_bots.setMinimumSize(QtCore.QSize(10, 10))
        self.lbl_bots.setObjectName("lbl_bots")
        self.horizontalLayout.addWidget(self.lbl_bots)
        self.cmb_bots = QtWidgets.QComboBox(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.cmb_bots.sizePolicy().hasHeightForWidth()
        )
        self.cmb_bots.setSizePolicy(sizePolicy)
        self.cmb_bots.setObjectName("cmb_bots")
        self.horizontalLayout.addWidget(self.cmb_bots)
        self.btn_add_bot = QtWidgets.QPushButton(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_add_bot.sizePolicy().hasHeightForWidth()
        )
        self.btn_add_bot.setSizePolicy(sizePolicy)
        self.btn_add_bot.setObjectName("btn_add_bot")
        self.horizontalLayout.addWidget(self.btn_add_bot)
        self.btn_save = QtWidgets.QPushButton(parent=conf_bot)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum,
            QtWidgets.QSizePolicy.Policy.Fixed,
        )
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_save.sizePolicy().hasHeightForWidth()
        )
        self.btn_save.setSizePolicy(sizePolicy)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tree_configuration = QtWidgets.QTreeWidget(parent=conf_bot)
        self.tree_configuration.setAnimated(True)
        self.tree_configuration.setObjectName("tree_configuration")
        self.tree_configuration.header().setVisible(True)
        self.tree_configuration.header().setMinimumSectionSize(60)
        self.verticalLayout.addWidget(self.tree_configuration)

        self.retranslateUi(conf_bot)
        QtCore.QMetaObject.connectSlotsByName(conf_bot)

    def retranslateUi(self, conf_bot):
        _translate = QtCore.QCoreApplication.translate
        conf_bot.setWindowTitle(_translate("conf_bot", "Config Bots"))
        self.lbl_bots.setText(_translate("conf_bot", "Bots"))
        self.btn_add_bot.setText(_translate("conf_bot", "New"))
        self.btn_save.setText(_translate("conf_bot", "Save"))
        self.tree_configuration.headerItem().setText(
            0, _translate("conf_bot", "Key")
        )
        self.tree_configuration.headerItem().setText(
            1, _translate("conf_bot", "Value")
        )
        self.tree_configuration.setSortingEnabled(False)
