# Form implementation generated from reading ui file 'apps/gui/resources/ui/console.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Libraries
from PyQt6 import QtCore, QtGui, QtWidgets


class ConsoleDesigner(object):
    def setupUi(self, consoleForm):
        consoleForm.setObjectName("consoleForm")
        consoleForm.resize(897, 520)
        consoleForm.setMinimumSize(QtCore.QSize(897, 520))
        consoleForm.setMaximumSize(QtCore.QSize(1920, 1080))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Button,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Light,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Midlight,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Dark,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(164, 163, 163))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Mid,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Text,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.BrightText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Base,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Window,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.Shadow,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.AlternateBase,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.ToolTipBase,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.ToolTipText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Active,
            QtGui.QPalette.ColorRole.PlaceholderText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Button,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Light,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Midlight,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Dark,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(164, 163, 163))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Mid,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Text,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.BrightText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Base,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Window,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.Shadow,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.AlternateBase,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ToolTipBase,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.ToolTipText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Inactive,
            QtGui.QPalette.ColorRole.PlaceholderText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.WindowText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Button,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Light,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(250, 250, 249))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Midlight,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Dark,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(164, 163, 163))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Mid,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Text,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.BrightText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(123, 122, 122))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ButtonText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Base,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Window,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.Shadow,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(246, 245, 244))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.AlternateBase,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ToolTipBase,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.ToolTipText,
            brush,
        )
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(
            QtGui.QPalette.ColorGroup.Disabled,
            QtGui.QPalette.ColorRole.PlaceholderText,
            brush,
        )
        consoleForm.setPalette(palette)
        consoleForm.setWindowTitle("Form")
        consoleForm.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers
        )
        self.btn_set_max_amount = QtWidgets.QPushButton(parent=consoleForm)
        self.btn_set_max_amount.setGeometry(QtCore.QRect(19, 300, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btn_set_max_amount.setFont(font)
        self.btn_set_max_amount.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_set_max_amount.setObjectName("btn_set_max_amount")
        self.btn_auto_bet = QtWidgets.QPushButton(parent=consoleForm)
        self.btn_auto_bet.setGeometry(QtCore.QRect(20, 390, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btn_auto_bet.setFont(font)
        self.btn_auto_bet.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_auto_bet.setToolTip("")
        self.btn_auto_bet.setObjectName("btn_auto_bet")
        self.label = QtWidgets.QLabel(parent=consoleForm)
        self.label.setGeometry(QtCore.QRect(30, 220, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=consoleForm)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lbl_balance = QtWidgets.QLabel(parent=consoleForm)
        self.lbl_balance.setGeometry(QtCore.QRect(90, 100, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_balance.setFont(font)
        self.lbl_balance.setObjectName("lbl_balance")
        self.lbl_profit = QtWidgets.QLabel(parent=consoleForm)
        self.lbl_profit.setGeometry(QtCore.QRect(90, 130, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setKerning(True)
        self.lbl_profit.setFont(font)
        self.lbl_profit.setObjectName("lbl_profit")
        self.label_4 = QtWidgets.QLabel(parent=consoleForm)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 61, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lbl_home_bet = QtWidgets.QLabel(parent=consoleForm)
        self.lbl_home_bet.setGeometry(QtCore.QRect(10, 20, 231, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_home_bet.setFont(font)
        self.lbl_home_bet.setObjectName("lbl_home_bet")
        self.lbl_bot_type = QtWidgets.QLabel(parent=consoleForm)
        self.lbl_bot_type.setGeometry(QtCore.QRect(10, 50, 231, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_bot_type.setFont(font)
        self.lbl_bot_type.setObjectName("lbl_bot_type")
        self.txt_max_amount_to_bet = QtWidgets.QLineEdit(parent=consoleForm)
        self.txt_max_amount_to_bet.setGeometry(QtCore.QRect(20, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_max_amount_to_bet.setFont(font)
        self.txt_max_amount_to_bet.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhPreferNumbers
        )
        self.txt_max_amount_to_bet.setFrame(False)
        self.txt_max_amount_to_bet.setObjectName("txt_max_amount_to_bet")
        self.line = QtWidgets.QFrame(parent=consoleForm)
        self.line.setGeometry(QtCore.QRect(10, 80, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=consoleForm)
        self.line_2.setGeometry(QtCore.QRect(10, 200, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(parent=consoleForm)
        self.line_3.setGeometry(QtCore.QRect(10, 360, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.gbox_graph = QtWidgets.QGroupBox(parent=consoleForm)
        self.gbox_graph.setGeometry(QtCore.QRect(260, 10, 621, 281))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.gbox_graph.setFont(font)
        self.gbox_graph.setTabletTracking(False)
        self.gbox_graph.setAcceptDrops(False)
        self.gbox_graph.setWhatsThis("")
        self.gbox_graph.setAutoFillBackground(False)
        self.gbox_graph.setFlat(False)
        self.gbox_graph.setCheckable(False)
        self.gbox_graph.setObjectName("gbox_graph")
        self.list_log = QtWidgets.QListWidget(parent=consoleForm)
        self.list_log.setGeometry(QtCore.QRect(260, 310, 481, 191))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.list_log.setFont(font)
        self.list_log.setObjectName("list_log")
        self.btn_auto_cash_out = QtWidgets.QPushButton(parent=consoleForm)
        self.btn_auto_cash_out.setGeometry(QtCore.QRect(20, 450, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.btn_auto_cash_out.setFont(font)
        self.btn_auto_cash_out.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_auto_cash_out.setToolTip("")
        self.btn_auto_cash_out.setObjectName("btn_auto_cash_out")
        self.label_5 = QtWidgets.QLabel(parent=consoleForm)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 71, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lbl_profit_per = QtWidgets.QLabel(parent=consoleForm)
        self.lbl_profit_per.setGeometry(QtCore.QRect(90, 160, 151, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.lbl_profit_per.setFont(font)
        self.lbl_profit_per.setObjectName("lbl_profit_per")
        self.groupBox = QtWidgets.QGroupBox(parent=consoleForm)
        self.groupBox.setGeometry(QtCore.QRect(750, 300, 131, 201))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.lbl_mul_1 = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_mul_1.setGeometry(QtCore.QRect(10, 20, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_mul_1.setFont(font)
        self.lbl_mul_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_mul_1.setObjectName("lbl_mul_1")
        self.lbl_mul_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_mul_2.setGeometry(QtCore.QRect(10, 50, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_mul_2.setFont(font)
        self.lbl_mul_2.setToolTip("")
        self.lbl_mul_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_mul_2.setObjectName("lbl_mul_2")
        self.lbl_mul_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_mul_3.setGeometry(QtCore.QRect(10, 80, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_mul_3.setFont(font)
        self.lbl_mul_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_mul_3.setObjectName("lbl_mul_3")
        self.lbl_mul_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_mul_4.setGeometry(QtCore.QRect(10, 110, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_mul_4.setFont(font)
        self.lbl_mul_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_mul_4.setObjectName("lbl_mul_4")
        self.lbl_mul_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_mul_5.setGeometry(QtCore.QRect(10, 140, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_mul_5.setFont(font)
        self.lbl_mul_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_mul_5.setObjectName("lbl_mul_5")
        self.lbl_mul_6 = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_mul_6.setGeometry(QtCore.QRect(10, 170, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.lbl_mul_6.setFont(font)
        self.lbl_mul_6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_mul_6.setObjectName("lbl_mul_6")
        self.btn_set_max_amount.raise_()
        self.btn_auto_bet.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lbl_profit.raise_()
        self.label_4.raise_()
        self.lbl_home_bet.raise_()
        self.lbl_bot_type.raise_()
        self.txt_max_amount_to_bet.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.lbl_balance.raise_()
        self.gbox_graph.raise_()
        self.list_log.raise_()
        self.btn_auto_cash_out.raise_()
        self.label_5.raise_()
        self.lbl_profit_per.raise_()
        self.groupBox.raise_()

        self.retranslateUi(consoleForm)
        QtCore.QMetaObject.connectSlotsByName(consoleForm)

    def retranslateUi(self, consoleForm):
        self.btn_set_max_amount.setText(_("Set Amount Bet"))  # noqa
        self.btn_auto_bet.setText(f"{_('AutoBet')} ON")  # noqa
        self.label.setText(_("Amount Bet"))  # noqa
        self.label_2.setText("Balance:")  # noqa
        self.lbl_balance.setText("0")  # noqa
        self.lbl_profit.setText("0")  # noqa
        self.label_4.setText("Profit:")  # noqa
        self.lbl_home_bet.setText("Demo")  # noqa
        self.lbl_bot_type.setText("Bot: Aggressive")  # noqa
        self.btn_auto_cash_out.setText(f"{_('Auto CashOut')} OFF")  # noqa
        self.gbox_graph.setTitle(_("Trend"))  # noqa
        self.label_5.setText("% Profit:")
        self.lbl_profit_per.setText("0")
        self.groupBox.setTitle(_("Multiplier/Position"))  # noqa
        self.groupBox.setToolTip(_("last multiplier position"))  # noqa
        self.lbl_mul_1.setText("0:0")
        self.lbl_mul_2.setText("0:0")
        self.lbl_mul_3.setText("0:0")
        self.lbl_mul_4.setText("0:0")
        self.lbl_mul_5.setText("0:0")
        self.lbl_mul_6.setText("0:0")
        self.gbox_graph.setToolTip(
            f"<html><head/><body><p><span>{_('Multiplicator')} trend</span></p></body></html>"  # noqa
        )
        self.groupBox.setToolTip(
            f"<html><head/><body><p>{_('Last multiplier positions. Format (multiplier:position)</p><p>If the position is -1, the multiplier was not found in all the analyzed rounds.')}</p></body></html>"  # noqa
        )
