# Form implementation generated from reading ui file 'apps/gui/resources/ui/parameter.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Libraries
from PyQt6 import QtCore, QtGui, QtWidgets


class ParameterDesigner(object):
    def setupUi(self, Parameters):
        Parameters.setObjectName("Parameters")
        Parameters.resize(409, 373)
        Parameters.setMinimumSize(QtCore.QSize(409, 373))
        Parameters.setMaximumSize(QtCore.QSize(409, 373))
        self.groupBox = QtWidgets.QGroupBox(parent=Parameters)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 351))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 90, 341, 22))
        self.label.setMinimumSize(QtCore.QSize(0, 22))
        self.label.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label.setObjectName("label")
        self.cmb_home_bet = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_home_bet.setGeometry(QtCore.QRect(20, 120, 351, 30))
        self.cmb_home_bet.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_home_bet.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_home_bet.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.cmb_home_bet.setObjectName("cmb_home_bet")
        self.cmb_home_bet.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 160, 341, 22))
        self.label_2.setMinimumSize(QtCore.QSize(0, 22))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_2.setObjectName("label_2")
        self.cmb_bot_type = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_bot_type.setGeometry(QtCore.QRect(20, 190, 351, 30))
        self.cmb_bot_type.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_bot_type.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_bot_type.setObjectName("cmb_bot_type")
        self.cmb_bot_type.addItem("")
        self.cmb_bot_type.addItem("")
        self.cmb_bot_type.addItem("")
        self.btn_start = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_start.setGeometry(QtCore.QRect(20, 290, 351, 41))
        self.btn_start.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_start.setMaximumSize(QtCore.QSize(16777215, 300))
        self.btn_start.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_start.setObjectName("btn_start")
        self.chk_use_credentials = QtWidgets.QCheckBox(parent=self.groupBox)
        self.chk_use_credentials.setGeometry(QtCore.QRect(20, 260, 341, 30))
        self.chk_use_credentials.setMinimumSize(QtCore.QSize(0, 30))
        self.chk_use_credentials.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setKerning(True)
        self.chk_use_credentials.setFont(font)
        self.chk_use_credentials.setMouseTracking(False)
        self.chk_use_credentials.setToolTipDuration(3)
        self.chk_use_credentials.setIconSize(QtCore.QSize(20, 20))
        self.chk_use_credentials.setChecked(True)
        self.chk_use_credentials.setObjectName("chk_use_credentials")
        self.chk_use_ai = QtWidgets.QCheckBox(parent=self.groupBox)
        self.chk_use_ai.setEnabled(False)
        self.chk_use_ai.setGeometry(QtCore.QRect(20, 230, 341, 30))
        self.chk_use_ai.setMinimumSize(QtCore.QSize(0, 30))
        self.chk_use_ai.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chk_use_ai.setMouseTracking(False)
        self.chk_use_ai.setToolTipDuration(3)
        self.chk_use_ai.setIconSize(QtCore.QSize(20, 20))
        self.chk_use_ai.setChecked(False)
        self.chk_use_ai.setObjectName("chk_use_ai")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 341, 22))
        self.label_3.setMinimumSize(QtCore.QSize(0, 22))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_3.setObjectName("label_3")
        self.cmb_game = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_game.setGeometry(QtCore.QRect(20, 50, 351, 30))
        self.cmb_game.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_game.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_game.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.cmb_game.setObjectName("cmb_game")
        self.cmb_game.addItem("")

        self.retranslateUi(Parameters)
        QtCore.QMetaObject.connectSlotsByName(Parameters)

    def retranslateUi(self, Parameters):
        Parameters.setWindowTitle(_("Parameters"))  # noqa
        self.label_3.setText(_("Game"))  # noqa
        self.label.setText(_("Home bet"))  # noqa
        self.cmb_home_bet.setItemText(0, "Demo")  # noqa
        self.label_2.setText(_("Bot"))  # noqa
        self.cmb_bot_type.setItemText(0, "Agressive")  # noqa
        self.btn_start.setText(_("Start"))  # noqa
        self.chk_use_credentials.setText(_("Use saved credentials"))  # noqa
        self.chk_use_ai.setText(_("Use AI"))  # noqa
