# Form implementation generated from reading ui file 'ui/parameter.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ParameterDesigner(object):
    def setupUi(self, Parameters):
        Parameters.setObjectName("Parameters")
        Parameters.resize(409, 399)
        self.groupBox = QtWidgets.QGroupBox(parent=Parameters)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 341, 22))
        self.label.setMinimumSize(QtCore.QSize(0, 22))
        self.label.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label.setObjectName("label")
        self.cmb_home_bet = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_home_bet.setGeometry(QtCore.QRect(20, 50, 351, 30))
        self.cmb_home_bet.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_home_bet.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_home_bet.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.cmb_home_bet.setObjectName("cmb_home_bet")
        self.cmb_home_bet.addItem("")
        self.cmb_home_bet.addItem("")
        self.cmb_home_bet.addItem("")
        self.cmb_home_bet.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 341, 22))
        self.label_2.setMinimumSize(QtCore.QSize(0, 22))
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_2.setObjectName("label_2")
        self.cmb_bot_type = QtWidgets.QComboBox(parent=self.groupBox)
        self.cmb_bot_type.setGeometry(QtCore.QRect(20, 130, 351, 30))
        self.cmb_bot_type.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_bot_type.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_bot_type.setObjectName("cmb_bot_type")
        self.cmb_bot_type.addItem("")
        self.cmb_bot_type.addItem("")
        self.cmb_bot_type.addItem("")
        self.chk_autoplay = QtWidgets.QCheckBox(parent=self.groupBox)
        self.chk_autoplay.setGeometry(QtCore.QRect(20, 180, 341, 30))
        self.chk_autoplay.setMinimumSize(QtCore.QSize(0, 30))
        self.chk_autoplay.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chk_autoplay.setToolTipDuration(3)
        self.chk_autoplay.setIconSize(QtCore.QSize(20, 20))
        self.chk_autoplay.setObjectName("chk_autoplay")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 220, 341, 22))
        self.label_3.setMinimumSize(QtCore.QSize(0, 22))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_3.setObjectName("label_3")
        self.txt_max_bet_amount = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_max_bet_amount.setGeometry(QtCore.QRect(20, 250, 351, 30))
        self.txt_max_bet_amount.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_max_bet_amount.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txt_max_bet_amount.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
        )
        self.txt_max_bet_amount.setMaxLength(6)
        self.txt_max_bet_amount.setObjectName("txt_max_bet_amount")
        self.btn_start = QtWidgets.QPushButton(parent=self.groupBox)
        self.btn_start.setGeometry(QtCore.QRect(20, 330, 351, 41))
        self.btn_start.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_start.setMaximumSize(QtCore.QSize(16777215, 300))
        self.btn_start.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_start.setObjectName("btn_start")
        self.chk_use_credentials = QtWidgets.QCheckBox(parent=self.groupBox)
        self.chk_use_credentials.setGeometry(QtCore.QRect(20, 290, 341, 30))
        self.chk_use_credentials.setMinimumSize(QtCore.QSize(0, 30))
        self.chk_use_credentials.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chk_use_credentials.setToolTipDuration(3)
        self.chk_use_credentials.setIconSize(QtCore.QSize(20, 20))
        self.chk_use_credentials.setChecked(True)
        self.chk_use_credentials.setObjectName("chk_use_credentials")

        self.retranslateUi(Parameters)
        QtCore.QMetaObject.connectSlotsByName(Parameters)

    def retranslateUi(self, Parameters):
        _translate = QtCore.QCoreApplication.translate
        Parameters.setWindowTitle(_translate("Parameters", "Parameters"))
        self.label.setText(_translate("Parameters", "Home bet"))
        self.cmb_home_bet.setItemText(0, _translate("Parameters", "Bet Play"))
        self.cmb_home_bet.setItemText(1, _translate("Parameters", "One win"))
        self.cmb_home_bet.setItemText(2, _translate("Parameters", "Demo"))
        self.cmb_home_bet.setItemText(3, _translate("Parameters", "Rivalo"))
        self.label_2.setText(_translate("Parameters", "Bot type"))
        self.cmb_bot_type.setItemText(0, _translate("Parameters", "Agressive"))
        self.cmb_bot_type.setItemText(1, _translate("Parameters", "Tight"))
        self.cmb_bot_type.setItemText(2, _translate("Parameters", "Loose"))
        self.chk_autoplay.setText(_translate("Parameters", "AutoPlay"))
        self.label_3.setText(_translate("Parameters", "Max bet amount"))
        self.btn_start.setText(_translate("Parameters", "Start"))
        self.chk_use_credentials.setText(
            _translate("Parameters", "Use saved credentials")
        )
