# Form implementation generated from reading ui file 'apps/gui/resources/ui/configurations.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Libraries
from PyQt6 import QtCore, QtGui, QtWidgets


class ConfigurationsDesigner(object):
    def setupUi(self, ConfigurationsDesigner):
        ConfigurationsDesigner.setObjectName("ConfigurationsDesigner")
        ConfigurationsDesigner.resize(412, 234)
        ConfigurationsDesigner.setMinimumSize(QtCore.QSize(412, 234))
        ConfigurationsDesigner.setMaximumSize(QtCore.QSize(412, 234))
        self.groupBox = QtWidgets.QGroupBox(parent=ConfigurationsDesigner)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 171))
        self.groupBox.setObjectName("groupBox")
        self.txt_len_bullish_game = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_len_bullish_game.setGeometry(QtCore.QRect(260, 40, 121, 21))
        self.txt_len_bullish_game.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
        )
        self.txt_len_bullish_game.setObjectName("txt_len_bullish_game")
        self.lbl_len_bullish_game = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_len_bullish_game.setGeometry(QtCore.QRect(10, 40, 240, 20))
        self.lbl_len_bullish_game.setObjectName("lbl_len_bullish_game")
        self.lbl_value_bullish_game = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_value_bullish_game.setGeometry(QtCore.QRect(10, 70, 240, 20))
        self.lbl_value_bullish_game.setObjectName("lbl_value_bullish_game")
        self.lbl_num_multiplier_in_bar = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_num_multiplier_in_bar.setGeometry(
            QtCore.QRect(10, 100, 240, 20)
        )
        self.lbl_num_multiplier_in_bar.setObjectName(
            "lbl_num_multiplier_in_bar"
        )
        self.txt_value_bullish_game = QtWidgets.QLineEdit(parent=self.groupBox)
        self.txt_value_bullish_game.setGeometry(QtCore.QRect(260, 70, 121, 21))
        self.txt_value_bullish_game.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
        )
        self.txt_value_bullish_game.setObjectName("txt_value_bullish_game")
        self.txt_num_multiplier_in_bar = QtWidgets.QLineEdit(
            parent=self.groupBox
        )
        self.txt_num_multiplier_in_bar.setGeometry(
            QtCore.QRect(260, 100, 121, 21)
        )
        self.txt_num_multiplier_in_bar.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
        )
        self.txt_num_multiplier_in_bar.setObjectName(
            "txt_num_multiplier_in_bar"
        )
        self.txt_multipliers_to_show = QtWidgets.QLineEdit(
            parent=self.groupBox
        )
        self.txt_multipliers_to_show.setGeometry(
            QtCore.QRect(260, 130, 121, 21)
        )
        self.txt_multipliers_to_show.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
        )
        self.txt_multipliers_to_show.setObjectName("txt_multipliers_to_show")
        self.lbl_multipliers_to_show = QtWidgets.QLabel(parent=self.groupBox)
        self.lbl_multipliers_to_show.setGeometry(
            QtCore.QRect(10, 130, 240, 20)
        )
        self.lbl_multipliers_to_show.setObjectName("lbl_multipliers_to_show")
        self.btn_save = QtWidgets.QPushButton(parent=ConfigurationsDesigner)
        self.btn_save.setGeometry(QtCore.QRect(280, 190, 100, 32))
        self.btn_save.setObjectName("btn_save")

        self.retranslateUi(ConfigurationsDesigner)
        QtCore.QMetaObject.connectSlotsByName(ConfigurationsDesigner)

    def retranslateUi(self, ConfigurationsForm):
        ConfigurationsForm.setWindowTitle(_("Configurations"))  # noqa
        self.groupBox.setTitle(_("Trend Graph Configuration"))  # noqa
        self.lbl_len_bullish_game.setText(
            _("Size to determine bullish game:")  # noqa
        )
        self.lbl_value_bullish_game.setText(
            _("Value to determine bullish game:")  # noqa
        )
        self.lbl_num_multiplier_in_bar.setText(
            _("Number of multipliers in graph:")  # noqa
        )
        self.lbl_multipliers_to_show.setText(
            _("Multipliers to show last positions:")  # noqa
        )
        self.btn_save.setText(_("Save"))  # noqa
