# Form implementation generated from reading ui file 'ui/credentials.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


# Libraries
from PyQt6 import QtCore, QtGui, QtWidgets


class CredentialDesigner(object):
    def setupUi(self, Credentials):
        Credentials.setObjectName("Credentials")
        Credentials.resize(450, 377)
        Credentials.setMinimumSize(QtCore.QSize(450, 377))
        Credentials.setMaximumSize(QtCore.QSize(450, 377))
        self.btn_dialog = QtWidgets.QDialogButtonBox(parent=Credentials)
        self.btn_dialog.setGeometry(QtCore.QRect(270, 340, 171, 32))
        self.btn_dialog.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.btn_dialog.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Ok
        )
        self.btn_dialog.setObjectName("btn_dialog")
        self.tab_credentials = QtWidgets.QTabWidget(parent=Credentials)
        self.tab_credentials.setGeometry(QtCore.QRect(10, 10, 431, 321))
        self.tab_credentials.setTabPosition(
            QtWidgets.QTabWidget.TabPosition.North
        )
        self.tab_credentials.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tab_credentials.setObjectName("tab_credentials")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lst_credentials_home_bet = QtWidgets.QListWidget(parent=self.tab)
        self.lst_credentials_home_bet.setGeometry(
            QtCore.QRect(120, 20, 291, 231)
        )
        self.lst_credentials_home_bet.setObjectName("lst_credentials_home_bet")
        item = QtWidgets.QListWidgetItem()
        self.lst_credentials_home_bet.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.lst_credentials_home_bet.addItem(item)
        self.btn_remove = QtWidgets.QPushButton(parent=self.tab)
        self.btn_remove.setGeometry(QtCore.QRect(8, 80, 101, 31))
        self.btn_remove.setObjectName("btn_remove")
        self.btn_remove_all = QtWidgets.QPushButton(parent=self.tab)
        self.btn_remove_all.setGeometry(QtCore.QRect(8, 120, 101, 31))
        self.btn_remove_all.setObjectName("btn_remove_all")
        self.tab_credentials.addTab(self.tab, "")
        self.page_crendential = QtWidgets.QWidget()
        self.page_crendential.setObjectName("page_crendential")
        self.label_4 = QtWidgets.QLabel(parent=self.page_crendential)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 341, 22))
        self.label_4.setMinimumSize(QtCore.QSize(0, 22))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(parent=self.page_crendential)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 341, 22))
        self.label_3.setMinimumSize(QtCore.QSize(0, 22))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label_3.setObjectName("label_3")
        self.txt_username = QtWidgets.QLineEdit(parent=self.page_crendential)
        self.txt_username.setGeometry(QtCore.QRect(20, 120, 391, 30))
        self.txt_username.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_username.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txt_username.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
        )
        self.txt_username.setMaxLength(-1)
        self.txt_username.setObjectName("txt_username")
        self.cmb_home_bet = QtWidgets.QComboBox(parent=self.page_crendential)
        self.cmb_home_bet.setGeometry(QtCore.QRect(20, 50, 391, 30))
        self.cmb_home_bet.setMinimumSize(QtCore.QSize(0, 30))
        self.cmb_home_bet.setMaximumSize(QtCore.QSize(16777215, 30))
        self.cmb_home_bet.setLayoutDirection(
            QtCore.Qt.LayoutDirection.LeftToRight
        )
        self.cmb_home_bet.setAutoFillBackground(False)
        self.cmb_home_bet.setObjectName("cmb_home_bet")
        self.cmb_home_bet.addItem("")
        self.btn_save = QtWidgets.QPushButton(parent=self.page_crendential)
        self.btn_save.setGeometry(QtCore.QRect(20, 220, 391, 41))
        self.btn_save.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_save.setMaximumSize(QtCore.QSize(16777215, 300))
        self.btn_save.setCursor(
            QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor)
        )
        self.btn_save.setObjectName("btn_save")
        self.label = QtWidgets.QLabel(parent=self.page_crendential)
        self.label.setGeometry(QtCore.QRect(20, 20, 341, 22))
        self.label.setMinimumSize(QtCore.QSize(0, 22))
        self.label.setMaximumSize(QtCore.QSize(16777215, 22))
        self.label.setObjectName("label")
        self.txt_password = QtWidgets.QLineEdit(parent=self.page_crendential)
        self.txt_password.setGeometry(QtCore.QRect(20, 180, 391, 30))
        self.txt_password.setMinimumSize(QtCore.QSize(0, 30))
        self.txt_password.setMaximumSize(QtCore.QSize(16777215, 30))
        self.txt_password.setInputMethodHints(
            QtCore.Qt.InputMethodHint.ImhDigitsOnly
            | QtCore.Qt.InputMethodHint.ImhHiddenText
            | QtCore.Qt.InputMethodHint.ImhNoAutoUppercase
            | QtCore.Qt.InputMethodHint.ImhNoPredictiveText
            | QtCore.Qt.InputMethodHint.ImhSensitiveData
        )
        self.txt_password.setMaxLength(-1)
        self.txt_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_password.setObjectName("txt_password")
        self.tab_credentials.addTab(self.page_crendential, "")

        self.retranslateUi(Credentials)
        self.tab_credentials.setCurrentIndex(1)
        self.btn_dialog.accepted.connect(Credentials.accept)  # type: ignore
        self.btn_dialog.rejected.connect(Credentials.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Credentials)
        Credentials.setTabOrder(
            self.tab_credentials, self.lst_credentials_home_bet
        )
        Credentials.setTabOrder(self.lst_credentials_home_bet, self.btn_remove)
        Credentials.setTabOrder(self.btn_remove, self.btn_remove_all)
        Credentials.setTabOrder(self.btn_remove_all, self.cmb_home_bet)
        Credentials.setTabOrder(self.cmb_home_bet, self.txt_username)
        Credentials.setTabOrder(self.txt_username, self.txt_password)
        Credentials.setTabOrder(self.txt_password, self.btn_save)

    def retranslateUi(self, Credentials):
        Credentials.setWindowTitle(_("Credentials"))  # noqa
        __sortingEnabled = self.lst_credentials_home_bet.isSortingEnabled()
        self.lst_credentials_home_bet.setSortingEnabled(False)
        item = self.lst_credentials_home_bet.item(0)
        item.setText("BetPlay")  # noqa
        item = self.lst_credentials_home_bet.item(1)
        item.setText("Otro")  # noqa
        self.lst_credentials_home_bet.setSortingEnabled(__sortingEnabled)
        self.btn_remove.setText(_("Remove"))  # noqa
        self.btn_remove_all.setText(_("Remove All"))  # noqa
        self.tab_credentials.setTabText(
            self.tab_credentials.indexOf(self.tab),
            _("Saved Credentials"),  # noqa
        )
        self.label_4.setText(_("Password"))  # noqa
        self.label_3.setText(_("Username"))  # noqa
        self.cmb_home_bet.setItemText(0, "Demo")  # noqa
        self.btn_save.setText(_("Save"))  # noqa
        self.label.setText(_("Home bet"))  # noqa
        self.tab_credentials.setTabText(
            self.tab_credentials.indexOf(self.page_crendential),
            _("Add Crendential"),  # noqa
        )
